version: "0.2"
dictionaryDefinitions:
  - name: polish-dict
    path: ./.cspell.pl.txt
    addWords: true
  - name: english-dict
    path: ./.cspell.en.txt
    addWords: true
overrides:
  - language:
      - en
    dictionaries:
      - english-dict
    filename: "**/*.{ts,js,json,md,yml}"
  - language:
      - pl
      - en
    dictionaries:
      - polish-dict
      - english-dict
    filename: src.assets/i18n/pl/*
