import {Texture, BaseTexture} from 'pixi.js';
import {HoldOptions} from "./platform/PlatformSpecific";
import {ValidLanguage} from "../src.framework/net/retrocade/camel/RecamelLang";
export type BitmapData = HTMLOrSVGImageElement | HTMLVideoElement | HTMLCanvasElement | ImageBitmap | Texture | BaseTexture;
export type CanvasImageSource = HTMLImageElement | HTMLVideoElement | HTMLCanvasElement | ImageBitmap;
export type BitmapDataWritable = CanvasRenderingContext2D;
export type CanvasImageSourceFragment = [CanvasImageSource, number, number, number, number];

export type StyleName = "Aboveground" | "City" | "Deep Spaces" | "Fortress" | "Foundation" | "Iceworks";
export type StyleTilesets = 0|1|2|3|4|5|6|7|8|9|10;

export const C = {
	holdResourceName(holdOptions: HoldOptions) {
		return C.RES_HOLD_PREFIX + holdOptions.id;
	},

	subtitleResourceName(holdOptions: HoldOptions) {
		return C.RES_HOLD_SUBTITLE_PREFIX + holdOptions.id;
	},

	localeResourceName(holdOptions: HoldOptions, language:ValidLanguage) {
		return `${C.RES_HOLD_LOCALE_PREFIX}${holdOptions.id}_${language}`;
	},

	MIN_INT: -2147483648,
	MAX_INT: 2147483647,

	RES_HOLD_PREFIX: 'RES_HOLD_',
	RES_HOLD_LOCALE_PREFIX: 'RES_HOLD_LANG_',
	RES_HOLD_SUBTITLE_PREFIX: 'RES_HOLD_SUBTITLE_',

	RES_SFX_BEETHROSCARED1: 'RES_SFX_BEETHROSCARED1',
	RES_SFX_BEETHROSCARED2: 'RES_SFX_BEETHROSCARED2',
	RES_SFX_BEETHROSCARED3: 'RES_SFX_BEETHROSCARED3',
	RES_SFX_BELL: 'RES_SFX_BELL',
	RES_SFX_BRAINSKILLED: 'RES_SFX_BRAINSKILLED',
	RES_SFX_BUTTONCLICK: 'RES_SFX_BUTTONCLICK',
	RES_SFX_CHECKPOINT: 'RES_SFX_CHECKPOINT',
	RES_SFX_CRUMBLYDESTROY1: 'RES_SFX_CRUMBLYDESTROY1',
	RES_SFX_CRUMBLYDESTROY2: 'RES_SFX_CRUMBLYDESTROY2',
	RES_SFX_CRUMBLYDESTROY3: 'RES_SFX_CRUMBLYDESTROY3',
	RES_SFX_EVILEYEWAKE1: 'RES_SFX_EVILEYEWAKE1',
	RES_SFX_EVILEYEWAKE2: 'RES_SFX_EVILEYEWAKE2',
	RES_SFX_EVILEYEWAKE3: 'RES_SFX_EVILEYEWAKE3',
	RES_SFX_GATES: 'RES_SFX_GATES',
	RES_SFX_HITOBSTACLE1: 'RES_SFX_HITOBSTACLE1',
	RES_SFX_HITOBSTACLE2: 'RES_SFX_HITOBSTACLE2',
	RES_SFX_HITOBSTACLE3: 'RES_SFX_HITOBSTACLE3',
	RES_SFX_MIMICPLACED: 'RES_SFX_MIMICPLACED',
	RES_SFX_MONSTERKILL1: 'RES_SFX_MONSTERKILL1',
	RES_SFX_MONSTERKILL2: 'RES_SFX_MONSTERKILL2',
	RES_SFX_MONSTERKILL3: 'RES_SFX_MONSTERKILL3',
	RES_SFX_MONSTERKILL4: 'RES_SFX_MONSTERKILL4',
	RES_SFX_MONSTERKILL5: 'RES_SFX_MONSTERKILL5',
	RES_SFX_MONSTERKILL6: 'RES_SFX_MONSTERKILL6',
	RES_SFX_MONSTERKILL7: 'RES_SFX_MONSTERKILL7',
	RES_SFX_MONSTERKILL8: 'RES_SFX_MONSTERKILL8',
	RES_SFX_MONSTERKILL9: 'RES_SFX_MONSTERKILL9',
	RES_SFX_ORBHIT: 'RES_SFX_ORBHIT',
	RES_SFX_PLAYERDEATH1: 'RES_SFX_PLAYERDEATH1',
	RES_SFX_PLAYERDEATH2: 'RES_SFX_PLAYERDEATH2',
	RES_SFX_POTIONDRANK: 'RES_SFX_POTIONDRANK',
	RES_SFX_ROOMCONQUERED1: 'RES_SFX_ROOMCONQUERED1',
	RES_SFX_ROOMCONQUERED2: 'RES_SFX_ROOMCONQUERED2',
	RES_SFX_ROOMCONQUERED3: 'RES_SFX_ROOMCONQUERED3',
	RES_SFX_SCROLLREAD: 'RES_SFX_SCROLLREAD',
	RES_SFX_SHORTHARPS: 'RES_SFX_SHORTHARPS',
	RES_SFX_STEP1: 'RES_SFX_STEP1',
	RES_SFX_STEP2: 'RES_SFX_STEP2',
	RES_SFX_STEP3: 'RES_SFX_STEP3',
	RES_SFX_SWORDSWING1: 'RES_SFX_SWORDSWING1',
	RES_SFX_SWORDSWING2: 'RES_SFX_SWORDSWING2',
	RES_SFX_SWORDSWING3: 'RES_SFX_SWORDSWING3',
	RES_SFX_TARSPLATTER1: 'RES_SFX_TARSPLATTER1',
	RES_SFX_TARSPLATTER2: 'RES_SFX_TARSPLATTER2',
	RES_SFX_TARSPLATTER3: 'RES_SFX_TARSPLATTER3',
	RES_SFX_TRAPDOOR1: 'RES_SFX_TRAPDOOR1',
	RES_SFX_TRAPDOOR2: 'RES_SFX_TRAPDOOR2',
	RES_SFX_TRAPDOOR3: 'RES_SFX_TRAPDOOR3',

	RES_MUSIC_AMBIENT_1: 'RES_MUSIC_AMBIENT_1',
	RES_MUSIC_AMBIENT_2: 'RES_MUSIC_AMBIENT_2',
	RES_MUSIC_AMBIENT_3: 'RES_MUSIC_AMBIENT_3',
	RES_MUSIC_WIN_LEVEL_1: 'RES_MUSIC_WIN_LEVEL_1',
	RES_MUSIC_WIN_LEVEL_2: 'RES_MUSIC_WIN_LEVEL_2',
	RES_MUSIC_WIN_LEVEL_3: 'RES_MUSIC_WIN_LEVEL_3',
	RES_MUSIC_ATTACK_1: 'RES_MUSIC_ATTACK_1',
	RES_MUSIC_ATTACK_2: 'RES_MUSIC_ATTACK_2',
	RES_MUSIC_ATTACK_3: 'RES_MUSIC_ATTACK_3',
	RES_MUSIC_ATTACK_4: 'RES_MUSIC_ATTACK_4',
	RES_MUSIC_ATTACK_5: 'RES_MUSIC_ATTACK_5',
	RES_MUSIC_ATTACK_6: 'RES_MUSIC_ATTACK_6',
	RES_MUSIC_PUZZLE_1: 'RES_MUSIC_PUZZLE_1',
	RES_MUSIC_PUZZLE_2: 'RES_MUSIC_PUZZLE_2',
	RES_MUSIC_PUZZLE_3: 'RES_MUSIC_PUZZLE_3',
	RES_MUSIC_PUZZLE_4: 'RES_MUSIC_PUZZLE_4',
	RES_MUSIC_PUZZLE_5: 'RES_MUSIC_PUZZLE_5',
	RES_MUSIC_PUZZLE_6: 'RES_MUSIC_PUZZLE_6',

	RES_MUSIC_AMBIENT: 'RES_MUSIC_AMBIENT',
	RES_MUSIC_ATTACK1: 'RES_MUSIC_ATTACK1',
	RES_MUSIC_ATTACK2: 'RES_MUSIC_ATTACK2',
	RES_MUSIC_PUZZLE1: 'RES_MUSIC_PUZZLE1',
	RES_MUSIC_PUZZLE2: 'RES_MUSIC_PUZZLE2',
	RES_MUSIC_WINLEVEL: 'RES_MUSIC_WINLEVEL',
	RES_MUSIC_CREDITS: 'RES_MUSIC_CREDITS',
	RES_MUSIC_TITLE: 'RES_MUSIC_TITLE',

	RES_LANG_CREDITS: 'RES_LANG_CREDITS',
	RES_LANG_COMMON_EN: 'RES_LANG_COMMON_EN',
	RES_LANG_COMMON_NL: 'RES_LANG_COMMON_NL',
	RES_LANG_COMMON_DE: 'RES_LANG_COMMON_DE',
	RES_LANG_COMMON_FI: 'RES_LANG_COMMON_FI',
	RES_LANG_COMMON_ES: 'RES_LANG_COMMON_ES',
	RES_LANG_COMMON_PT: 'RES_LANG_COMMON_PT',
	RES_LANG_COMMON_FR: 'RES_LANG_COMMON_FR',
	RES_LANG_COMMON_RU: 'RES_LANG_COMMON_RU',
	RES_LANG_COMMON_PL: 'RES_LANG_COMMON_PL',
	RES_LANG_HOLD_EN: 'RES_LANG_HOLD_EN',
	RES_LANG_HOLD_NL: 'RES_LANG_HOLD_NL',
	RES_LANG_HOLD_DE: 'RES_LANG_HOLD_DE',
	RES_LANG_HOLD_FI: 'RES_LANG_HOLD_FI',
	RES_LANG_HOLD_ES: 'RES_LANG_HOLD_ES',
	RES_LANG_HOLD_PT: 'RES_LANG_HOLD_PT',
	RES_LANG_HOLD_FR: 'RES_LANG_HOLD_FR',
	RES_LANG_HOLD_RU: 'RES_LANG_HOLD_RU',
	RES_LANG_HOLD_PL: 'RES_LANG_HOLD_PL',

	RES_TUTORIAL_KEYS: 'RES_KEYS',

	RES_BUTTON_SYSTEM: 'RES_BUTTON_SYSTEM',
	RES_BUTTON_DOWN_SYSTEM: 'RES_BUTTON_DOWN_SYSTEM',
	RES_WINDOW_BG_SYSTEM: 'RES_WINDOW_BG_SYSTEM',
	RES_TOOLTIP_BG_SYSTEM: 'RES_TOOLTIP_BG_SYSTEM',
	RES_INPUT_BG_SYSTEM: 'RES_INPUT_BG_SYSTEM',

	RES_ABOVEGROUND_WALL: 'RES_ABOVEGROUND_WALL',
	RES_ABOVEGROUND_FLOOR: 'RES_ABOVEGROUND_FLOOR',
	RES_ABOVEGROUND_FLOORALT: 'RES_ABOVEGROUND_FLOORALT',
	RES_ABOVEGROUND_FLOORDIRT: 'RES_ABOVEGROUND_FLOORDIRT',
	RES_ABOVEGROUND_FLOORGRASS: 'RES_ABOVEGROUND_FLOORGRASS',
	RES_ABOVEGROUND_FLOORMOSAIC: 'RES_ABOVEGROUND_FLOORMOSAIC',
	RES_ABOVEGROUND_FLOORROAD: 'RES_ABOVEGROUND_FLOORROAD',
	RES_ABOVEGROUND_PIT: 'RES_ABOVEGROUND_PIT',
	RES_ABOVEGROUND_PITSIDE: 'RES_ABOVEGROUND_PITSIDE',
	RES_ABOVEGROUND_PITSIDESMALL: 'RES_ABOVEGROUND_PITSIDESMALL',
	RES_ABOVEGROUND_TILES: 'RES_ABOVEGROUND_TILES',

	RES_CITY_WALL: 'RES_CITY_WALL',
	RES_CITY_FLOOR: 'RES_CITY_FLOOR',
	RES_CITY_FLOORALT: 'RES_CITY_FLOORALT',
	RES_CITY_FLOORDIRT: 'RES_CITY_FLOORDIRT',
	RES_CITY_FLOORGRASS: 'RES_CITY_FLOORGRASS',
	RES_CITY_FLOORMOSAIC: 'RES_CITY_FLOORMOSAIC',
	RES_CITY_FLOORROAD: 'RES_CITY_FLOORROAD',
	RES_CITY_PIT: 'RES_CITY_PIT',
	RES_CITY_PITSIDE: 'RES_CITY_PITSIDE',
	RES_CITY_PITSIDESMALL: 'RES_CITY_PITSIDESMALL',
	RES_CITY_TILES: 'RES_CITY_TILES',

	RES_DEEP_SPACES_WALL: 'RES_DEEP_SPACES_WALL',
	RES_DEEP_SPACES_FLOOR: 'RES_DEEP_SPACES_FLOOR',
	RES_DEEP_SPACES_FLOORALT: 'RES_DEEP_SPACES_FLOORALT',
	RES_DEEP_SPACES_FLOORDIRT: 'RES_DEEP_SPACES_FLOORDIRT',
	RES_DEEP_SPACES_FLOORGRASS: 'RES_DEEP_SPACES_FLOORGRASS',
	RES_DEEP_SPACES_FLOORMOSAIC: 'RES_DEEP_SPACES_FLOORMOSAIC',
	RES_DEEP_SPACES_FLOORROAD: 'RES_DEEP_SPACES_FLOORROAD',
	RES_DEEP_SPACES_PIT: 'RES_DEEP_SPACES_PIT',
	RES_DEEP_SPACES_PITSIDE: 'RES_DEEP_SPACES_PITSIDE',
	RES_DEEP_SPACES_PITSIDESMALL: 'RES_DEEP_SPACES_PITSIDESMALL',
	RES_DEEP_SPACES_TILES: 'RES_DEEP_SPACES_TILES',

	RES_FORTRESS_WALL: 'RES_FORTRESS_WALL',
	RES_FORTRESS_FLOOR: 'RES_FORTRESS_FLOOR',
	RES_FORTRESS_FLOORALT: 'RES_FORTRESS_FLOORALT',
	RES_FORTRESS_FLOORDIRT: 'RES_FORTRESS_FLOORDIRT',
	RES_FORTRESS_FLOORGRASS: 'RES_FORTRESS_FLOORGRASS',
	RES_FORTRESS_FLOORMOSAIC: 'RES_FORTRESS_FLOORMOSAIC',
	RES_FORTRESS_FLOORROAD: 'RES_FORTRESS_FLOORROAD',
	RES_FORTRESS_PIT: 'RES_FORTRESS_PIT',
	RES_FORTRESS_PITSIDE: 'RES_FORTRESS_PITSIDE',
	RES_FORTRESS_PITSIDESMALL: 'RES_FORTRESS_PITSIDESMALL',
	RES_FORTRESS_TILES: 'RES_FORTRESS_TILES',

	RES_FOUNDATION_WALL: 'RES_FOUNDATION_WALL',
	RES_FOUNDATION_FLOOR: 'RES_FOUNDATION_FLOOR',
	RES_FOUNDATION_FLOORALT: 'RES_FOUNDATION_FLOORALT',
	RES_FOUNDATION_FLOORDIRT: 'RES_FOUNDATION_FLOORDIRT',
	RES_FOUNDATION_FLOORGRASS: 'RES_FOUNDATION_FLOORGRASS',
	RES_FOUNDATION_FLOORMOSAIC: 'RES_FOUNDATION_FLOORMOSAIC',
	RES_FOUNDATION_FLOORROAD: 'RES_FOUNDATION_FLOORROAD',
	RES_FOUNDATION_PIT: 'RES_FOUNDATION_PIT',
	RES_FOUNDATION_PITSIDE: 'RES_FOUNDATION_PITSIDE',
	RES_FOUNDATION_PITSIDESMALL: 'RES_FOUNDATION_PITSIDESMALL',
	RES_FOUNDATION_TILES: 'RES_FOUNDATION_TILES',

	RES_ICEWORKS_WALL: 'RES_ICEWORKS_WALL',
	RES_ICEWORKS_FLOOR: 'RES_ICEWORKS_FLOOR',
	RES_ICEWORKS_FLOORALT: 'RES_ICEWORKS_FLOORALT',
	RES_ICEWORKS_FLOORDIRT: 'RES_ICEWORKS_FLOORDIRT',
	RES_ICEWORKS_FLOORGRASS: 'RES_ICEWORKS_FLOORGRASS',
	RES_ICEWORKS_FLOORMOSAIC: 'RES_ICEWORKS_FLOORMOSAIC',
	RES_ICEWORKS_FLOORROAD: 'RES_ICEWORKS_FLOORROAD',
	RES_ICEWORKS_PIT: 'RES_ICEWORKS_PIT',
	RES_ICEWORKS_PITSIDE: 'RES_ICEWORKS_PITSIDE',
	RES_ICEWORKS_PITSIDESMALL: 'RES_ICEWORKS_PITSIDESMALL',
	RES_ICEWORKS_TILES: 'RES_ICEWORKS_TILES',

	RES_PRELOADER_BG: 'RES_PRELOADER_BG',
	RES_GENERAL_TILES: 'RES_GENERAL_TILES',
	RES_EFFECTS: 'RES_EFFECTS',
	RES_BOLTS: 'RES_BOLTS',
	RES_FACES: 'RES_FACES',
	RES_EYES: 'RES_EYES',
	RES_SCROLLS: 'RES_SCROLLS',
	RES_GAME_SCREEN: 'RES_GAME_SCREEN',
	RES_MENU_BG: 'RES_MENU_BG',
	RES_LEVEL_START_BG: 'RES_LEVEL_START_BG',
	RES_TITLE_BG: 'RES_TITLE_BG',
	RES_LOGO_CARAVEL: 'RES_LOGO_CARAVEL',
	RES_LOGO_RETROCADE: 'RES_LOGO_RETROCADE',
	RES_LOGO_GAME: 'RES_LOGO_GAME',
	RES_ACHIEVEMENT: 'RES_ACHIEVEMENT',
	RES_LOCK: 'RES_LOCK',
	RES_MUS_AMBIENT: 'RES_MUS_AMBIENT',
	RES_MUS_ATTACK_1: 'RES_MUS_ATTACK_1',
	RES_MUS_ATTACK_2: 'RES_MUS_ATTACK_2',
	RES_MUS_PUZZLE_1: 'RES_MUS_PUZZLE_1',
	RES_MUS_PUZZLE_2: 'RES_MUS_PUZZLE_2',
	RES_MUS_WINLEVEL: 'RES_MUS_WINLEVEL',
	RES_MUS_CREDITS: 'RES_MUS_CREDITS',
	RES_MUS_TITLE: 'RES_MUS_TITLE',

	// Tiles
	T_EMPTY: 0,
	T_FLOOR: 1,
	T_PIT: 2,
	T_STAIRS: 3,
	T_WALL: 4,
	T_WALL_BROKEN: 5,
	T_DOOR_C: 6,
	T_DOOR_G: 7,
	T_DOOR_R: 8,
	T_DOOR_Y: 9,
	T_DOOR_YO: 10,
	T_TRAPDOOR: 11,
	T_OBSTACLE: 12,
	T_ARROW_N: 13,
	T_ARROW_NE: 14,
	T_ARROW_E: 15,
	T_ARROW_SE: 16,
	T_ARROW_S: 17,
	T_ARROW_SW: 18,
	T_ARROW_W: 19,
	T_ARROW_NW: 20,
	T_POTION_I: 21,
	T_POTION_M: 22,
	T_SCROLL: 23,
	T_ORB: 24,
	T_SNK_EW: 25,
	T_SNK_NS: 26,
	T_SNK_NW: 27,
	T_SNK_NE: 28,
	T_SNK_SW: 29,
	T_SNK_SE: 30,
	T_SNKT_S: 31,
	T_SNKT_W: 32,
	T_SNKT_N: 33,
	T_SNKT_E: 34,
	T_TAR: 35,
	T_CHECKPOINT: 36,

	T_DOOR_B: 37,
	T_POTION_SP: 38,
	T_FLOW_SOURCE: 39,
	T_FLOW_INNER: 40,
	T_FLOW_EDGE: 41,
	T_LIGHT_CEILING: 42,
	T_BOMB: 43,
	T_FUSE: 44,
	T_NODIAGONAL: 45,
	T_TOKEN: 46,
	T_TUNNEL_N: 47,
	T_TUNNEL_S: 48,
	T_MIRROR: 49,
	T_POTION_C: 50,
	T_POTION_D: 51,
	T_PLATFORM_W: 52,
	T_PLATFORM_P: 53,
	T_FLOOR_MOSAIC: 54,
	T_FLOOR_ROAD: 55,
	T_FLOOR_GRASS: 56,
	T_FLOOR_DIRT: 57,
	T_FLOOR_ALT: 58,
	T_WALL_MASTER: 59,
	T_MUD: 60,
	T_STAIRS_UP: 61,
	T_WALL_HIDDEN: 62,
	T_TUNNEL_E: 63,
	T_TUNNEL_W: 64,
	T_FLOOR_IMAGE: 65,
	T_WALL2: 66,
	T_WATER: 67,
	T_DOOR_GO: 68,
	T_DOOR_CO: 69,
	T_DOOR_RO: 70,
	T_DOOR_BO: 71,
	T_TRAPDOOR_WATER: 72,
	T_GOO: 73,
	T_LIGHT: 74,
	T_HOT: 75,
	T_GEL: 76,
	T_STATION: 77,
	T_PRESSPLATE: 78,
	T_BRIDGE: 79,
	T_BRIDGE_H: 80,
	T_BRIDGE_V: 81,
	T_PIT_IMAGE: 82,
	T_WALL_IMAGE: 83,
	T_DARK_CEILING: 84,
	T_WALLLIGHT: 85,
	T_EMPTY_F: 86,

	M_ROACH: 0,
	M_QROACH: 1,
	M_ROACH_EGG: 2,
	M_GOBLIN: 3,
	M_NEATHER: 4,
	M_WWING: 5,
	M_EYE: 6,
	M_SERPENT: 7,
	M_TARMOTHER: 8,
	M_TARBABY: 9,
	M_BRAIN: 10,
	M_MIMIC: 11,
	M_SPIDER: 12,
	M_SERPENTG: 13,
	M_SERPENTB: 14,
	M_ROCKGOLEM: 15,
	M_WATERSKIPPER: 16,
	M_SKIPPERNEST: 17,
	M_AUMTLICH: 18,
	M_CLONE: 19,
	M_DECOY: 20,
	M_WUBBA: 21,
	M_SEEP: 22,
	M_STALWART: 23,
	M_HALPH: 24,
	M_SLAYER: 25,
	M_FEGUNDO: 26,
	M_FEGUNDOASHES: 27,
	M_GUARD: 28,
	M_CHARACTER: 29,
	M_MUDMOTHER: 30,
	M_MUDBABY: 31,
	M_GELMOTHER: 32,
	M_GELBABY: 33,
	M_CITIZEN: 34,
	M_ROCKGIANT: 35,
	M_HALPH2: 36,
	M_SLAYER2: 37,
	M_NEGOTIATOR: 10000,
	M_CITIZEN1: 10001,
	M_CITIZEN2: 10002,
	M_GOBLINKING: 10003,
	M_INSTRUCTOR: 10004,
	M_MUDCOORDINATOR: 10005,
	M_TARTECHNICIAN: 10006,
	M_EYE_ACTIVE: 10007,
	M_BEETHRO: 10008,
	M_CITIZEN3: 10009,
	M_CITIZEN4: 10010,
	M_BEETHRO_IN_DISGUISE: 10011,

	MONSTER_TYPES: 38,

	// Commands

	CMD_UNSPECIFIED: 0,
	CMD_N: 1,
	CMD_NE: 2,
	CMD_W: 3,
	CMD_E: 5,
	CMD_SW: 6,
	CMD_S: 7,
	CMD_SE: 8,
	CMD_C: 9,
	CMD_CC: 10,
	CMD_NW: 11,
	CMD_WAIT: 12,
	CMD_RESTART: 14,
	CMD_YES: 15,
	CMD_NO: 16,
	CMD_RESTART_FULL: 17,
	CMD_RESTART_PART: 18,
	CMD_UNDO: 19,
	CMD_CLONE: 20,
	CMD_DOUBLE: 21,
	CMD_ANSWER: 22,
	CMD_COMMAND_COUNT: 23,


	// Orientation

	NW: 0,
	N: 1,
	NE: 2,
	W: 3,
	NO_ORIENTATION: 4,
	E: 5,
	SW: 6,
	S: 7,
	SE: 8,
	ORIENTATION_COUNT: 9,

	CID_MONSTER_KILLED_PLAYER: 0,
	CID_SNAKE_DIED_FROM_TRUNCATION: 1,
	CID_MONSTER_DIED_FROM_STAB: 2,
	CID_EXIT_ROOM: 3,
	CID_EXIT_LEVEL_PENDING: 4,
	CID_WIN_GAME: 5,
	CID_CONQUER_ROOM: 6,
	CID_COMPLETE_LEVEL: 7,
	CID_STEP_ON_SCROLL: 8,
	CID_EGG_HATCHED: 9,
	CID_HALPH_INTERRUPTED: 10,
	CID_HALPH_HURRY_UP: 11,
	CID_PLOTS: 12,
	CID_TRAPDOOR_REMOVED: 13,
	CID_TARSTUFF_DESTROYED: 14,
	CID_TAR_GREW: 15,
	CID_MONSTER_SPOKE: 16,
	CID_MONSTER_EXITS_ROOM: 17,
	CID_EXIT_ROOM_PENDING: 18,
	CID_CRUMBLY_WALL_DESTROYED: 19,
	CID_ORB_ACTIVATED_BY_PLAYER: 20,
	CID_ORB_ACTIVATED_BY_DOUBLE: 21,
	CID_ROOM_CONQUER_PENDING: 22,
	CID_DRANK_POTION: 23,
	CID_DOUBLE_PLACED: 24,
	CID_HIT_OBSTACLE: 25,
	CID_SWING_SWORD: 26,
	CID_SCARED: 27,
	CID_STEP: 28,
	CID_SWORDSMAN_AFRAID: 29,
	CID_SWORDSMAN_AGGRESSIVE: 30,
	CID_SWORDSMAN_NORMAL: 31,
	CID_EVIL_EYE_WOKE: 32,
	CID_TAR_BABY_FORMED: 33,
	CID_CHECKPOINT_ACTIVATED: 34,
	CID_NEATHER_LAUGHING: 35,
	CID_NEATHER_FRUSTRATED: 36,
	CID_NEATHER_SCARED: 37,
	CID_SWORDSMAN_TIRED: 38,
	CID_ALL_TRAPDOORS_REMOVED: 39,
	CID_ALL_TAR_REMOVED: 40,
	CID_ROOM_EXIT_LOCKED: 41,
	CID_MONSTER_PIECE_STABBED: 42,
	CID_FUSE_BURNING: 43,
	CID_BOMB_EXPLODED: 44,
	CID_EXPLOSION: 45,
	CID_EXPLOSION_KILLED_PLAYER: 46,
	CID_NPC_TYPE_CHANGE: 47,
	CID_PLAYER_FROZEN: 48,
	CID_ZOMBIE_GAZE: 49,
	CID_WUBBA_STABBED: 50,
	CID_SLAYER_COMBAT: 51,
	CID_HALPH_ENTERED: 52,
	CID_HALPH_DIED: 53,
	CID_HALPH_FOLLOWING: 54,
	CID_HALPH_WAITING: 55,
	CID_HALPH_STRIKING: 56,
	CID_HALPH_CANT_OPEN: 57,
	CID_SLAYER_ENTERED: 58,
	CID_WISP_ON_PLAYER: 59,
	CID_SECRET_ROOM_FOUND: 60,
	CID_SPEECH: 61,
	CID_MUD_GREW: 62,
	CID_MUD_BABY_FORMED: 63,
	CID_SWORDFIGHT: 64,
	CID_SET_MUSIC: 65,
	CID_ALL_BRAINS_REMOVED: 66,
	CID_TUNNEL: 67,
	CID_ORB_ACTIVATED: 68,
	CID_FEGUNDO_TO_ASH: 69,
	CID_ASH_TO_FEGUNDO: 70,
	CID_AMBIENT_SOUND: 71,
	CID_MIRROR_SHATTERED: 72,
	CID_OBJECT_FELL: 73,
	CID_PLAYER_BURNED: 74,
	CID_MONSTER_BURNED: 75,
	CID_GEL_GREW: 76,
	CID_GEL_BABY_FORMED: 77,
	CID_NPC_BEETHRO_DIED: 78,
	CID_PRESSURE_PLATE: 79,
	CID_PRESSURE_PLATE_RELEASED: 80,
	CID_CRITICAL_NPC_DIED: 81,
	CID_BRIAR_KILLED_PLAYER: 82,
	CID_TOKEN_TOGGLED: 83,
	CID_LIGHT_TOGGLED: 84,
	CID_SPLASH: 85,
	CID_NPC_KILLED: 86,
	CID_OBJECT_BUILT: 87,
	CID_PLAY_VIDEO: 88,
	CID_BRIAR_EXPANDED: 89,
	CID_ORB_DAMAGED: 90,
	CID_HOLD_MASTERED: 91,
	CID_BUMPED_MASTER_WALL: 92,
	CID_BLACK_GATES_TOGGLED: 93,
	CID_RED_GATES_TOGGLED: 94,
	CID_SWORDSMAN_STABBED_MONSTER: 95,
	CID_ENTER_ROOM: 96,
	CID_SUBMIT_SCORE: 97,
	CID_ROOM_FIRST_VISIT: 98,
	CID_COUNT: 99,

	CIDA_PLAYER_LEFT_ROOM: [0],

	CIDA_PLAYER_DIED: [0],

	CIDA_MONSTER_DIED: [0],

	CIDA_MONSTER_STABBED: [0],

	/** 0 - Opaque, 1 - Transparent, 2 - Monster, 3 - Floor **/
	TILE_LAYER: [
		1, //T_EMPTY         0
		0, //T_FLOOR         1
		0, //T_PIT           2
		0, //T_STAIRS        3
		0, //T_WALL          4
		0, //T_WALL_B        5
		0, //T_DOOR_C        6
		0, //T_DOOR_M        7
		0, //T_DOOR_R        8
		0, //T_DOOR_Y        9
		0, //T_DOOR_YO       10
		0, //T_TRAPDOOR      11
		1, //T_OBSTACLE      12 //was muin layer 0 before v2.0
		3, //T_ARROW_N       13 //arrows were in layer 1 before v3.0
		3, //T_ARROW_NE      14
		3, //T_ARROW_E       15
		3, //T_ARROW_SE      16
		3, //T_ARROW_S       17
		3, //T_ARROW_SW      18
		3, //T_ARROW_W       19
		3, //T_ARROW_NW      20
		1, //T_POTION_I      21
		1, //T_POTION_M      22
		1, //T_SCROLL        23
		1, //T_ORB           24
		2, //T_SNK_EW        25
		2, //T_SNK_NS        26
		2, //T_SNK_NW        27
		2, //T_SNK_NE        28
		2, //T_SNK_SW        29
		2, //T_SNK_SE        30
		2, //T_SNKT_S        31
		2, //T_SNKT_W        32
		2, //T_SNKT_N        33
		2, //T_SNKT_E        34
		1, //T_TAR           35
		0, //T_CHECKPOINT    36

		0, //T_DOOR_B        37
		1, //T_POTION_SP     38
		1, //T_FLOW_SOURCE   39
		1, //T_FLOW_INNER    40
		1, //T_FLOW_EDGE     41
		3, //T_LIGHT_CEILING 42 //front end only -- show on f-layer menu
		1, //T_BOMB          43
		1, //T_FUSE          44
		3, //T_NODIAGONAL    45 //was in layer 1 before v3.0
		1, //T_TOKEN         46
		0, //T_TUNNEL_N      47
		0, //T_TUNNEL_S      48
		1, //T_MIRROR        49
		1, //T_POTION_C      50
		1, //T_POTION_D      51
		0, //T_PLATFORM_W    52
		0, //T_PLATFORM_P    53
		0, //T_FLOOR_M       54
		0, //T_FLOOR_ROAD    55
		0, //T_FLOOR_GRASS   56
		0, //T_FLOOR_DIRT    57
		0, //T_FLOOR_ALT     58
		0, //T_WALL_M        59
		1, //T_MUD           60
		0, //T_STAIRS_UP     61
		0, //T_WALL_H        62
		0, //T_TUNNEL_E      63
		0, //T_TUNNEL_W      64
		0, //T_FLOOR_IMAGE   65
		0,	//T_WALL2         66
		0,	//T_WATER         67
		0, //T_DOOR_GO       68
		0, //T_DOOR_CO       69
		0, //T_DOOR_RO       70
		0, //T_DOOR_BO       71
		0, //T_TRAPDOOR2     72
		0, //T_GOO           73
		1, //T_LIGHT			74
		0, //T_HOT           75
		1, //T_GEL           76
		1, //T_STATION       77
		0, //T_PRESSPLATE    78
		0, //T_BRIDGE        79
		0, //T_BRIDGE_H      80
		0, //T_BRIDGE_V      81
		0, //T_PIT_IMAGE     82
		0, //T_WALL_IMAGE    83
		3, //T_DARK_CEILING  84 //front end only -- show on f-layer menu
		3, //T_WALLLIGHT     85 //front end only -- show on f-layer menu
		0, //T_SHALLOW_WATER 86
		1, //T_HORN_SQUAD    87
		1, //T_HORN_SOLIDER  88

		3,  //T_EMPTY_F       TOTAL+2
	],

	// ORB ACTION TYPE
	OAT_PLAYER: 0,
	OAT_MONSTER: 1,
	OAT_ITEM: 2,
	OAT_SCRIPT_ORB: 3,
	OAT_PRESSURE_PLATE: 4,
	OAT_PRESSURE_PLATE_UP: 5,
	OAT_SCRIPT_PLATE: 6,

	// ORB ACTION
	OA_NULL: 0,
	OA_TOGGLE: 1,
	OA_OPEN: 2,
	OA_CLOSE: 3,

	MOVEMENT_GROUND: 0,
	MOVEMENT_AIR: 1,
	MOVEMENT_WALL: 2,
	MOVEMENT_WATER: 3,

	TURNS_PER_CYCLE: 30,
	DEFAULT_SMELL_RANGE: 5,

	TAR_NO: 0,
	TAR_OLD: 1,
	TAR_NEW: 2,

	FONT_FAMILY: "tom",

	REND_WALL_TEXTURE: 0x01,
	REND_WALL_HIDDEN_SECRET: 0x02,

	REND_PIT_IS_SIDE: 0x80000000,
	REND_PIT_IS_SIDE_SMALL: 0x40000000,
	REND_PIT_ADD_SHADOW: 0x20000000,
	REND_PIT_COORDS_MASK: 0x1FFFFFFF, // Masked to remove the above two flags
	REND_PIT_COORD_MULTIP: 0x00000020, // Multiplier for coordinates

	CC_APPEAR: 0,
	CC_APPEAR_AT: 1,
	CC_MOVE_TO: 2,
	CC_WAIT: 3,
	CC_WAIT_FOR_CUE_EVENT: 4,
	CC_WAIT_FOR_RECT: 5,
	CC_SPEECH: 6,
	CC_IMPERATIVE: 7,
	CC_DISAPPEAR: 8,
	CC_TURN_INTO_MONSTER: 9,
	CC_FACE_DIRECTION: 10,
	CC_WAIT_FOR_NOT_RECT: 11,
	CC_WAIT_FOR_DOOR_TO: 12,
	CC_LABEL: 13,
	CC_GOTO: 14,
	CC_GOTO_IF: 15,
	CC_WAIT_FOR_MONSTER: 16,
	CC_WAIT_FOR_NOT_MONSTER: 17,
	CC_WAIT_FOR_TURN: 18,
	CC_WAIT_FOR_CLEAN_ROOM: 19,
	CC_WAIT_FOR_PLAYER_TO_FACE: 20,
	CC_ACTIVATE_ITEM_AT: 21,
	CC_END_SCRIPT: 22,
	CC_WAIT_FOR_HALPH: 23,
	CC_WAIT_FOR_NOT_HALPH: 24,
	CC_WAIT_FOR_CHARACTER: 25,
	CC_WAIT_FOR_NOT_CHARACTER: 26,
	CC_FLUSH_SPEECH: 27,
	CC_QUESTION: 28,
	CC_SET_MUSIC: 29,
	CC_END_SCRIPT_ON_EXIT: 30,
	CC_IF: 31,
	CC_IF_ELSE: 32,
	CC_IF_END: 33,
	CC_LEVEL_ENTRANCE: 34,
	CC_VAR_SET: 35,
	CC_WAIT_FOR_VAR: 36,
	CC_SET_PLAYER_APPEARANCE: 37,
	CC_CUT_SCENE: 38,
	CC_MOVE_REL: 39,
	CC_SET_PLAYER_SWORD: 40,
	CC_ANSWER_OPTION: 41,
	CC_BUILD_MARKER: 42,
	CC_AMBIENT_SOUND: 43,
	CC_AMBIENT_SOUND_AT: 44,
	CC_WAIT_FOR_NO_BUILDING: 45,
	CC_PLAY_VIDEO: 46,
	CC_WAIT_FOR_PLAYER_TO_MOVE: 47,
	CC_WAIT_FOR_PLAYER_TO_TOUCH_ME: 48,
	CC_SET_NPC_APPEARANCE: 49,
	CC_COUNT: 50,

	IMP_VULNERABLE: 0,
	IMP_INVULNERABLE: 1,
	IMP_MISSION_CRITICAL: 2,
	IMP_REQUIRED_TO_CONQUER: 3,
	IMP_DIE: 4,
	IMP_DIE_SPECIAL: 5,
	IMP_SAFE: 6,
	IMP_DEADLY: 7,
	IMP_SWORD_SAFE_TO_PLAYER: 8,
	IMP_END_WHEN_KILLED: 9,
	IMP_FLEXIBLE_BEELINING: 10,
	IMP_DIRECT_BEELINING: 11,

	FLAG_PLAYER: 0x00000001,
	FLAG_HALPH: 0x00000002,
	FLAG_MONSTER: 0x00000004,
	FLAG_NPC: 0x00000008,
	FLAG_PDOUBLE: 0x00000010,
	FLAG_SELF: 0x00000020,
	FLAG_SLAYER: 0x00000040,
	FLAG_BEETHRO: 0x00000080,
	FLAG_STALWART: 0x00000100,

	UVT_byte: 0,
	UVT_char_string: 1,
	UVT_deprecated_dword: 2,
	UVT_int: 3,
	UVT_deprecated_uchar: 4,
	UVT_uint: 5,
	UVT_wchar_string: 6,
	UVT_byte_buffer: 7,
	UVT_bool: 8,
	UVT_unknown: 9,

	SPEAK_Beethro: 0,	//don't change these constants
	SPEAK_Citizen1: 6,
	SPEAK_Citizen2: 7,
	SPEAK_Citizen3: 45,
	SPEAK_Citizen4: 46,
	SPEAK_Custom: 5,
	SPEAK_EyeActive: 15,
	SPEAK_GoblinKing: 8, //deprecated
	SPEAK_Instructor: 10, //deprecated
	SPEAK_MudCoordinator: 11, //deprecated
	SPEAK_Negotiator: 3, //deprecated
	SPEAK_None: 4,
	SPEAK_TarTechnician: 13, //deprecated
	SPEAK_BeethroInDisguise: 47,
	SPEAK_Self: 50,
	SPEAK_Halph: 1,
	SPEAK_Slayer: 2,
	SPEAK_Goblin: 9,
	SPEAK_RockGolem: 12,
	SPEAK_Guard: 14,
	SPEAK_Stalwart: 17,
	SPEAK_Roach: 18,
	SPEAK_QRoach: 19,
	SPEAK_RoachEgg: 20,
	SPEAK_WWing: 21,
	SPEAK_Eye: 22,
	SPEAK_Serpent: 23,
	SPEAK_TarMother: 24,
	SPEAK_TarBaby: 25,
	SPEAK_Brain: 26,
	SPEAK_Mimic: 27,
	SPEAK_Spider: 28,
	SPEAK_SerpentG: 29,
	SPEAK_SerpentB: 30,
	SPEAK_WaterSkipper: 31,
	SPEAK_WaterSkipperNest: 32,
	SPEAK_Aumtlich: 33,
	SPEAK_Clone: 34,
	SPEAK_Decoy: 35,
	SPEAK_Wubba: 36,
	SPEAK_Seep: 37,
	SPEAK_Fegundo: 38,
	SPEAK_FegundoAshes: 39,
	SPEAK_MudMother: 40,
	SPEAK_MudBaby: 41,
	SPEAK_GelMother: 42,
	SPEAK_GelBaby: 43,
	SPEAK_Citizen: 16,
	SPEAK_RockGiant: 44,
	SPEAK_Slayer2: 48,
	SPEAK_Halph2: 49,
	SPEAK_Count: 51,

	VAR_Assign: 0,
	VAR_Inc: 1,
	VAR_Dec: 2,
	VAR_AssignText: 3,
	VAR_AppendText: 4,
	VAR_MultiplyBy: 5,
	VAR_DivideBy: 6,
	VAR_Mod: 7,

	VAR_Equals: 0,
	VAR_Greater: 1,
	VAR_Less: 2,
	VAR_EqualsText: 3,

	SPEAKERS: [0],

	SPEAKER_COLOUR: [
		0xFFFF00,  //Beethro
		0xFFF719,  //Halph
		0xFFC0FF,  //Slayer
		0xD0BAA3,  //Negotiator
		0xFFFFFF,  //(none)
		0xFFFFFF,  //(custom)
		0xC0C0FF,  //Citizen 1
		0xFF80FF,  //Citizen 2
		0x40FF40,  //Goblin King
		0x20FF20,  //Goblin
		0x40FFFF,  //Instructor
		0xFF6400,  //Mud Coordinator
		0xC08060,  //Rock golem
		0xA380FF,  //Tar Technician
		0xFF6060,  //Guard
		0xFFFFFF,  //Evil eye (active)
		0xD2D2C8,  //Citizen
		0xFFFF80,  //Stalwart
		0xA0A0A0,  //roach
		0xC0C0C0,  //roach queen
		0xA0A0A0,	//roach egg
		0x808080,  //wwing
		0xFFFFFF,  //evil eye
		0xFF6060,  //red serpent
		0x4040C0,  //tar mother
		0x4040C0,  //tarbaby
		0xFF2020,  //brain
		0x23C8DD,  //mimic
		0x60C0C0,  //spider
		0x60FF60,  //green serpent
		0x8080FF,  //blue serpent
		0x303030,  //water skipper
		0x303030,  //water skipper nest
		0xDDDDDD,  //aumtlich
		0xFFFF28,  //clone
		0xA0A0A0,  //decoy
		0xFFFFFF,  //wubba
		0xC4C4C4,  //seep
		0xC0C05C,  //fegundo
		0xC0C05C,  //fegundo ashes
		0xC04040,  //mud mother
		0xC04040,  //mudbaby
		0x40C040,  //gel mother
		0x40C040,  //gelbaby
		0xC08060,  //rock giant
		0xFFC0FF,  //Citizen 3
		0xFF80FF,  //Citizen 4
		0xFFFF00,  //Beethro in disguise
		0xFFC0FF,  //Slayer2
		0xFFF719,   //Halph2
	],

	SETTING_VOLUME_EFFECTS: "volEff",
	SETTING_VOLUME_VOICES: "volVoic",
	SETTING_VOLUME_MUSIC: "volMus",
	SETTING_REPEAT_VISUAL: "repeat_visual",
	SETTING_REPEAT_DELAY: "repeat_delay",
	SETTING_CNET_NAME: "cName",
	SETTING_CNET_PASS: "cPass",
	SETTING_MOVE_COUNTER: "moveCounter",

	SETTINGS_SAVE_SIZE: 1024 * 1024 * 256,

	MUSIC_TITLE: "musicTitle",
	MUSIC_AMBIENT: "musicAmbient",
	MUSIC_PUZZLE: "musicPuzzle",
	MUSIC_ACTION: "musicAction",
	MUSIC_OUTRO: "musicOutro",
	MUSIC_LEVEL_EXIT: "musicExit",

	HOLD_KDDL1: "kddl1",
	HOLD_KDDL2: "kddl2",
	HOLD_KDDL3: "kddl3",
	HOLD_KDDL4: "kddl4",
	HOLD_KDDL5: "kddl5",
	HOLD_KDDL6: "kddl6",
	HOLD_THE_ANCIENT_PALACE: "tap",
	HOLD_SPIDER: "spider",
	HOLD_LOADER: "no_hold",
};


C.CIDA_PLAYER_LEFT_ROOM = [
	C.CID_EXIT_ROOM_PENDING,
	C.CID_EXIT_ROOM,
	C.CID_EXIT_LEVEL_PENDING,
	C.CID_WIN_GAME,
	C.CID_MONSTER_KILLED_PLAYER,
	C.CID_EXPLOSION_KILLED_PLAYER,
	C.CID_BRIAR_KILLED_PLAYER,
	C.CID_HALPH_DIED,
	C.CID_PLAYER_BURNED,
	C.CID_NPC_BEETHRO_DIED,
	C.CID_CRITICAL_NPC_DIED,
];

C.CIDA_PLAYER_DIED = [
	C.CID_MONSTER_KILLED_PLAYER,
	C.CID_EXPLOSION_KILLED_PLAYER,
	C.CID_BRIAR_KILLED_PLAYER,
	C.CID_HALPH_DIED,
	C.CID_PLAYER_BURNED,
	C.CID_NPC_BEETHRO_DIED,
	C.CID_CRITICAL_NPC_DIED,
];

C.CIDA_MONSTER_DIED = [
	C.CID_SNAKE_DIED_FROM_TRUNCATION,
	C.CID_MONSTER_DIED_FROM_STAB,
	C.CID_MONSTER_EXITS_ROOM,
	C.CID_MONSTER_BURNED,
];

C.CIDA_MONSTER_STABBED = [
	C.CID_MONSTER_DIED_FROM_STAB,
	C.CID_MONSTER_PIECE_STABBED,
	C.CID_TARSTUFF_DESTROYED,
];
C.SPEAKERS = [
	C.M_BEETHRO, C.M_HALPH, C.M_SLAYER, C.M_NEGOTIATOR, -2, -2,
	C.M_CITIZEN1, C.M_CITIZEN2, C.M_GOBLINKING, C.M_GOBLIN,
	C.M_INSTRUCTOR, C.M_MUDCOORDINATOR, C.M_ROCKGOLEM, C.M_TARTECHNICIAN, C.M_GUARD, C.M_EYE,
	C.M_CITIZEN, C.M_STALWART, C.M_ROACH, C.M_QROACH, C.M_ROACH_EGG, C.M_WWING, C.M_EYE,
	C.M_SERPENT, C.M_TARMOTHER, C.M_TARBABY, C.M_BRAIN, C.M_MIMIC, C.M_SPIDER,
	C.M_SERPENTG, C.M_SERPENTB, C.M_WATERSKIPPER, C.M_SKIPPERNEST, C.M_AUMTLICH, C.M_CLONE,
	C.M_DECOY, C.M_WUBBA, C.M_SEEP, C.M_FEGUNDO, C.M_FEGUNDOASHES, C.M_MUDMOTHER,
	C.M_MUDBABY, C.M_GELMOTHER, C.M_GELBABY, C.M_ROCKGIANT, C.M_CITIZEN3, C.M_CITIZEN4,
	C.M_BEETHRO_IN_DISGUISE, C.M_SLAYER2, C.M_HALPH2,
];

export enum HoldId {
	KDDL1 = "kddl1",
	KDDL2 = "kddl2",
	KDDL3 = "kddl3",
	KDDL4 = "kddl4",
	KDDL5 = "kddl5",
	KDDL6 = "kddl6",
	TheAncientPalace = 'the-ancient-palace',
}